# Generated by Django 3.1.2 on 2022-04-20 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_profesional'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publicacion',
            fields=[
                ('id_publicacion', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=50)),
                ('fecha_publicacion', models.DateField()),
                ('categoria', models.IntegerField(choices=[[0, 'Alimentacion'], [1, 'Medicamentos'], [2, 'Agenda Medica'], [3, 'Fonoaudiologia']])),
                ('autor', models.IntegerField(choices=[[0, 'Admin'], [1, 'Staff']])),
                ('texto', models.TextField()),
                ('imagen', models.ImageField(null=True, upload_to='publicacion')),
            ],
            options={
                'verbose_name': 'Publicacion',
                'verbose_name_plural': 'Publicaciones',
            },
        ),
        migrations.AlterModelOptions(
            name='profesional',
            options={'verbose_name': 'Profesional', 'verbose_name_plural': 'Profesionales'},
        ),
    ]
