# Generated by Django 3.1.2 on 2022-04-21 15:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0004_auto_20220420_1653'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('rutpaciente', models.CharField(max_length=30)),
                ('nombrepaciente', models.CharField(max_length=30)),
                ('apellidopatpaciente', models.CharField(max_length=30)),
                ('apellidomatpaciente', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('telefono', models.CharField(max_length=30)),
                ('whatsapp', models.CharField(max_length=30)),
                ('telegram', models.CharField(max_length=30)),
                ('id_app_usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Paciente',
                'verbose_name_plural': 'Pacientes',
            },
        ),
    ]
