# Generated by Django 3.1.2 on 2022-04-22 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_paciente_profesional'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fonoaudiologo_paciente',
            options={'verbose_name': 'Fonoaudiologo - Paciente', 'verbose_name_plural': 'Fonoaudiologo - Paciente'},
        ),
        migrations.AlterModelOptions(
            name='paciente_profesional',
            options={'verbose_name': 'Paciente - Profesional', 'verbose_name_plural': 'Paciente - Profesional'},
        ),
        migrations.AddField(
            model_name='paciente_profesional',
            name='id_tipo_usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='app.tipo_usuario'),
            preserve_default=False,
        ),
    ]
