# Generated by Django 3.1.2 on 2022-04-22 20:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0008_auto_20220422_1629'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fonoaudiologo_paciente',
            name='apellidomatpaciente',
        ),
        migrations.RemoveField(
            model_name='fonoaudiologo_paciente',
            name='apellidopatpaciente',
        ),
        migrations.RemoveField(
            model_name='fonoaudiologo_paciente',
            name='nombrepaciente',
        ),
        migrations.AddField(
            model_name='fonoaudiologo_paciente',
            name='idapp_paciente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='app.paciente', verbose_name='Rut Paciente'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fonoaudiologo_paciente',
            name='id_app_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Id Usuario'),
        ),
        migrations.AlterField(
            model_name='paciente_profesional',
            name='id_tipo_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.tipo_usuario', verbose_name='Tipo usuario Profesional'),
        ),
        migrations.AlterField(
            model_name='paciente_profesional',
            name='idapp_paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.paciente', verbose_name='Rut Paciente'),
        ),
        migrations.AlterField(
            model_name='paciente_profesional',
            name='idapp_profesional',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.profesional', verbose_name='Rut Profesional'),
        ),
    ]
