# Generated by Django 3.1.2 on 2022-04-25 23:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0009_auto_20220422_1658'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enfermeria_paciente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombrepaciente', models.CharField(max_length=30, verbose_name='Nombre Paciente')),
                ('apeliidopaternopaci', models.CharField(max_length=30, verbose_name='Apellido Paterno Paciente')),
                ('apellidomaternopaci', models.CharField(max_length=30, verbose_name='Apellido Materno Paciente')),
                ('fecha_contactabilidad', models.DateField()),
                ('bitacora_contactabilidad', models.TextField()),
                ('idapp_usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Id Usuario')),
            ],
            options={
                'verbose_name': 'Enfermeria - Paciente',
                'verbose_name_plural': 'Enfermeria - Paciente',
            },
        ),
    ]
