# Generated by Django 3.1.2 on 2022-04-26 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_enfermeria_paciente'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicamento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombrelab', models.CharField(max_length=30, verbose_name='Nombre Laboratorio')),
                ('nombremedicamen', models.CharField(max_length=30, verbose_name='Nombre Medicamento')),
                ('dosismedicamento', models.CharField(max_length=40, verbose_name='Dosis Medicamento')),
                ('cantidaddisplay', models.IntegerField(verbose_name='Cantidad Medicamento Display')),
            ],
            options={
                'verbose_name': 'Medicamento',
                'verbose_name_plural': 'Medicamentos',
            },
        ),
        migrations.RenameField(
            model_name='enfermeria_paciente',
            old_name='idapp_usuario',
            new_name='id_app_usuario',
        ),
        migrations.RemoveField(
            model_name='enfermeria_paciente',
            name='apeliidopaternopaci',
        ),
        migrations.RemoveField(
            model_name='enfermeria_paciente',
            name='apellidomaternopaci',
        ),
        migrations.RemoveField(
            model_name='enfermeria_paciente',
            name='nombrepaciente',
        ),
        migrations.AddField(
            model_name='enfermeria_paciente',
            name='idapp_paciente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='app.paciente', verbose_name='Rut Paciente'),
            preserve_default=False,
        ),
    ]
