# Generated by Django 3.1.2 on 2022-04-27 03:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_medicamentocompra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicamento',
            name='cantidaddisplay',
            field=models.CharField(max_length=30, verbose_name='Cantidad Medicamento Display'),
        ),
        migrations.AlterField(
            model_name='medicamentocompra',
            name='idapp_medicamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.medicamento', verbose_name='Medicamento/Laboratorio/Dosis/'),
        ),
    ]
