# Generated by Django 3.1.2 on 2022-04-27 18:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0013_auto_20220426_2351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enfermeria_paciente',
            name='idapp_paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.paciente', verbose_name='Rut / Nombre Paciente'),
        ),
        migrations.AlterField(
            model_name='fonoaudiologo_paciente',
            name='idapp_paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.paciente', verbose_name='Rut / Nombre Paciente'),
        ),
        migrations.AlterField(
            model_name='medicamentocompra',
            name='idapp_medicamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.medicamento', verbose_name='Medicamento/Laboratorio/Dosis/Cant.Display'),
        ),
        migrations.AlterField(
            model_name='medicamentocompra',
            name='idapp_paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.paciente', verbose_name='Rut / Nombre Paciente'),
        ),
        migrations.AlterField(
            model_name='paciente_profesional',
            name='idapp_paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.paciente', verbose_name='Rut / Nombre Paciente'),
        ),
        migrations.AlterField(
            model_name='paciente_profesional',
            name='idapp_profesional',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.profesional', verbose_name='Rut / Nombre Profesional'),
        ),
        migrations.CreateModel(
            name='Neurologia_Paciente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_consulta', models.DateField(verbose_name='Fecha consulta')),
                ('comentario', models.TextField(verbose_name='Comentarios Consulta')),
                ('id_app_usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Id Usuario')),
                ('idapp_medicamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.medicamento', verbose_name='Medicamento recomendado')),
                ('idapp_paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.paciente', verbose_name='Rut / Nombre Paciente')),
            ],
            options={
                'verbose_name': 'Neurologia - Paciente',
                'verbose_name_plural': 'Neurologia - Pacientes',
            },
        ),
    ]
