# Generated by Django 3.1.2 on 2022-05-02 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20220428_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacion',
            name='estado',
            field=models.IntegerField(choices=[[0, 'En espera'], [1, 'Visible']], default=0),
            preserve_default=False,
        ),
    ]
